[tool.black]
target-version = ["py313"]
line-length = 88
skip-string-normalization = true

[tool.ruff]
target-version = "py313"
line-length = 88
select = ["E", "F", "I"]
ignore = ["E501"]

[tool.mypy]
python_version = "3.13"
warn_return_any = true
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-q --disable-warnings"
testpaths = ["tests"]

[tool.coverage.run]
branch = true
source = ["genai_scaffolding_pro"]

[tool.coverage.report]
show_missing = true
skip_covered = true
fail_under = 70
