name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # for OIDC
      
    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pytest pytest-cov ruff black mypy

      - name: Lint
        run: |
          ruff check .
          black --check .

      - name: Typecheck
        run: |
          mypy genai_scaffolding_pro || true

      - name: Tests (with coverage + threshold)
        run: |
          pytest \
            --cov=genai_scaffolding_pro \
            --cov-report=xml \
            --cov-report=term-missing \
            --cov-fail-under=70 \
            --maxfail=1 --disable-warnings

      - name: Upload coverage to Codecov (OIDC)
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          use_oidc: true
          fail_ci_if_error: true

      - name: Build Docker
        run: |
          docker build -t genai-scaffolding:ci .